
# SEO settings
title: "Bi"
title2: "dda" # default: ""
description: "Data Science | NLP | Life."
keywords: "Jekyll, theme, free, download, SEO, blog, web, minimalist, thinkspace"
url: http://ambicapramod.github.io # site url
baseurl: "" # apply repo name if use it under gh-pages branch
# baseurl: null # apply null if repo name is something like username.github.io

google_analytics: UA-XXXXX-XX
repo: http://github.com/heiswayi/thinkspace
disqus_shortname: "hnbloggithub"
twitter_username: "HeiswayiNrird"
comments: true

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

source: ./
destination: ./_site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : "Ambica Pramod"
  job      : "Student in VIT University , Chennai"
  bio      : "A smooth sea never made a skilled sailor."
  thumb    : /images/author.jpg
  email    : ambicapramod@gmail.com	
  url      : ambicapramod.github.io
  github   : http://github.com/ambicapramod
  twitter  : 
  facebook : https://www.facebook.com/http404error
  linkedin : http://linkedin.com/in/ambicapramod

# social settings
og_locale: "en_US"
twitter_card: ""
twitter_site: ""

gems:
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
